apiVersion: v1
kind: Pod
metadata:
  name: myapp-ngnix
  labels:
    name: myapp-ngnix
spec:
  containers:
  - name: ngnix-container
    image: ngnix
    resources:
      limits:   #Hard limit for the container
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80 #container port
