apiVersion: v1
kind: Pod
metadata:
  name: myapp-ngnix
  labels:
    name: myapp-ngnix
spec:
  containers:
  - name: nginx-container
    image: nginx
    resources:
      requests:  # Soft limit for the contianer to start
        memory: "64Mi"
        cpu: "100m"
      limits:   #Hard limit for the container
        memory: "128Mi"
        cpu: "200m"
    ports:
      - containerPort: 80 #container port
