apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-testing
spec:
  template:
    metadata:
      name: myapp
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-nginx
        image: nginx
        ports:
        - containerPort: 80
  replicas: 3
  selector:
    matchLabels:
      app: myapp