apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-testing
spec:
  template:
    metadata:
      name: myapp-nginx
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp-nginx
          image: nginx
          ports:
            - containerPort: 80
  replicas: 2